version: "3.8"

services:
  postgres:
    image: postgres:17.0
    ports:
      - 15432:5432
    volumes:
      - ./local/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
